package com.ascoder1109.legalsaathi.entities;

public enum LawyerSpecialization {
    CRIMINAL_LAWYER,
    CIVIL_LAWYER,
    CORPORATE_LAWYER,
    FAMILY_LAWYER,
    TAX_LAWYER,
    INTELLECTUAL_PROPERTY_LAWYER,
    ENVIRONMENTAL_LAWYER,
    LABOR_LAWYER,
    PUBLIC_INTEREST_LAWYER,
    MEDICAL_MALPRACTICE_LAWYER,
    BANKRUPTCY_LAWYER,
    CYBER_LAWYER,
    ESTATE_PLANNING_LAWYER,
    WORKERS_COMPENSATION_LAWYER,
    MERGER_AND_ACQUISITION_LAWYER,
    MILITARY_LAWYER,
    CONTRACT_LAWYER,
    GOVERNMENT_LAWYER,
    IMMIGRATION_LAWYER
}
