// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqTeLMqEnakBIqHFB5ymsYas0PSy8NLGc',
    appId: '1:824436368646:web:5f7872c971f990fad7aa87',
    messagingSenderId: '824436368646',
    projectId: 'legalsaathi-e6ec1',
    authDomain: 'legalsaathi-e6ec1.firebaseapp.com',
    storageBucket: 'legalsaathi-e6ec1.appspot.com',
    measurementId: 'G-R9TBLYWYMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZGmUdm-Ikwsh6ZRPfBtkhkEnXa-sRvLY',
    appId: '1:824436368646:android:60a5959a16235d96d7aa87',
    messagingSenderId: '824436368646',
    projectId: 'legalsaathi-e6ec1',
    storageBucket: 'legalsaathi-e6ec1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcBODPCGsaqFXCnF9j5Ne72-DtB3NNDIA',
    appId: '1:824436368646:ios:d1b1b44661de3757d7aa87',
    messagingSenderId: '824436368646',
    projectId: 'legalsaathi-e6ec1',
    storageBucket: 'legalsaathi-e6ec1.appspot.com',
    iosBundleId: 'com.example.legalsaathi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcBODPCGsaqFXCnF9j5Ne72-DtB3NNDIA',
    appId: '1:824436368646:ios:d1b1b44661de3757d7aa87',
    messagingSenderId: '824436368646',
    projectId: 'legalsaathi-e6ec1',
    storageBucket: 'legalsaathi-e6ec1.appspot.com',
    iosBundleId: 'com.example.legalsaathi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqTeLMqEnakBIqHFB5ymsYas0PSy8NLGc',
    appId: '1:824436368646:web:f383fab71fe6c877d7aa87',
    messagingSenderId: '824436368646',
    projectId: 'legalsaathi-e6ec1',
    authDomain: 'legalsaathi-e6ec1.firebaseapp.com',
    storageBucket: 'legalsaathi-e6ec1.appspot.com',
    measurementId: 'G-D2R6ZCDYN6',
  );
}
